In [2]:
import numpy as np

In [4]:
x = np.random.random(1000000)

In [9]:
print(np.mean(x))

0.5000524897079442


In [11]:
x = np.array([1,2,3,4])
print(x.dtype)
print(x.shape)
type(x)

int64
(4,)


numpy.ndarray

In [12]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y.shape)

(3, 3)


In [13]:
x = np.array([1,1.2,1.35,4.8],dtype=np.int64)

In [14]:
print(x.dtype)

int64


In [15]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
x = np.zeros((3,4),dtype=np.int64)

In [17]:
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [18]:
x = np.ones((3,4))

In [19]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
print(np.full((3,4),5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
x = np.eye(5)

In [23]:
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
print(np.diag([5,1,2,4]))

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 4]]


In [29]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
x  = np.arange(4,8)
print(x)

[4 5 6 7]


In [32]:
x = np.arange(1,8,2)
print(x)

[1 3 5 7]


In [33]:
x = np.linspace(1,8,20,endpoint=False)
print(x)

[1.         1.36842105 1.73684211 2.10526316 2.47368421 2.84210526
 3.21052632 3.57894737 3.94736842 4.31578947 4.68421053 5.05263158
 5.42105263 5.78947368 6.15789474 6.52631579 6.89473684 7.26315789
 7.63157895 8.        ]


In [34]:
x = np.arange(10)

In [35]:
x = np.reshape(x,(2,5))
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [36]:
 x = np.random.random((3,2))
print(x)

[[0.9734599  0.85424622]
 [0.07425282 0.69548832]
 [0.6401571  0.48129589]]


In [37]:
x = np.random.randint(4,15,(3,2))
print(x)

[[ 9  9]
 [10  4]
 [14  8]]


In [38]:
x = np.random.normal(0,1,size=(1000,1000))
print(x)


[[ 0.65121598 -0.41864881 -0.95050567 ... -0.44628768  0.76261178
  -1.54931924]
 [-1.76977064 -0.64128227  0.04135914 ... -0.44454756  0.39413129
   1.31644173]
 [-0.24699486 -1.06555572 -0.17489448 ...  0.23662138  0.68385895
  -0.51660112]
 ...
 [ 0.6331578   0.2845168  -0.2281548  ... -0.10999091 -0.46881324
   1.195847  ]
 [ 0.24578505 -0.1592337   0.63207501 ... -0.29804681 -0.71821153
  -1.03775005]
 [-0.82718262 -0.34453976 -0.3009614  ... -0.66989765 -1.17186113
  -1.76073614]]


In [39]:
print(x.mean())
print(x.std())
print(x.min())
print(x.max())

-0.0005997906930831239
1.0005644075895843
-4.85770729870576
4.8800671708680925


In [40]:
print(np.linspace(2,32,16).reshape(4,4))

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]


In [41]:
x = np.linspace(2,32,16).reshape(4,4)
print(x[0,0])

2.0


In [52]:
x = np.linspace(2,32,16).reshape(4,4)
x = np.delete(x,[0,1],axis=0)
x = np.delete(x,[0,2],axis=1)
x = np.append(x,[[34,36],[38,40]],axis=0)
x = np.append(x,[[18],[20],[22],[24]],axis=1)
x = np.insert(x,1,[22,32,22],axis=0)
x = np.insert(x,1,[[22],[32],[22]],axis=1)
print(x)

[[20. 22. 32. 22. 24. 18.]
 [22. 22. 32. 22. 32. 22.]
 [28. 22. 32. 22. 32. 20.]
 [34. 22. 32. 22. 36. 22.]
 [38. 22. 32. 22. 40. 24.]]


In [55]:
x = np.random.randint(1,7,(2,2))
y = np.random.randint(1,7,(1,2))
print(np.vstack((x,y)))
print(np.hstack((x,y.reshape(2,1))))

[[4 6]
 [6 6]
 [4 4]]
[[4 6 4]
 [6 6 4]]


In [56]:
x = np.arange(1,21).reshape(4,5)
z = x[1:2,3:4]
print(z)

[[9]]


In [59]:
z = x[:,2:3].copy()
print(np.unique(z))

[ 3  8 13 18]


In [60]:
x = np.arange(1,21).reshape(4,5)
print(x[x<=7])

[1 2 3 4 5 6 7]


In [61]:
print(x[x>=7])

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [63]:
print(x[(x>=7)& (x<12)])

[ 7  8  9 10 11]


In [66]:
x = np.arange(1,20)
y = np.arange(1,20,3)
print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[ 1  4  7 10 13 16 19]
[ 2  3  5  6  8  9 11 12 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [70]:
x = np.random.randint(1,8,size=(10,))
print(np.sort(np.unique(x)))

[1 2 3 5 7]


In [71]:
x = np.random.randint(1,8,size=(5,5))
print(np.sort(x,axis=0))
print(np.sort(x,axis=1))

[[1 1 1 4 3]
 [2 2 3 4 5]
 [3 2 3 7 6]
 [4 2 6 7 6]
 [4 5 6 7 7]]
[[2 3 6 7 7]
 [1 2 3 4 4]
 [1 3 4 5 5]
 [1 3 4 6 7]
 [2 2 6 6 7]]


In [72]:
x = np.arange(1,26)
print(x[x%2 == 1])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [77]:
x = np.arange(1,4)
y = np.arange(4,7)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))
print(np.exp(x))
print(np.power(x,2))
print(x.sum())

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[1 4 9]
6
